Repository XcodesOrg/xcodes, pull requests merged in 2021-12, with the labels that each got.

#166 Fix broken link to `swift-argument-parser`
  README.md
Labels: chore

#168 Fixing issue with downloading Release Candidate builds
  Sources/XcodesKit/Version+Xcode.swift
  Tests/XcodesKitTests/Version+XcodeTests.swift
Labels: bugfix

#172 Setting universal build
  Makefile
Labels: enhancement
