Repository XcodesOrg/xcodes, pull requests merged in 2022-10, with the labels that each got.

#227 Use mocks when writing the cache file in unit tests
  Sources/XcodesKit/Environment.swift
  Sources/XcodesKit/XcodeList.swift
  Tests/XcodesKitTests/Environment+Mock.swift
Labels: hacktoberfest

#226 Update the cached list of available Xcodes if it's more than 24 hours old
  Sources/XcodesKit/Environment.swift
  Sources/XcodesKit/XcodeInstaller.swift
  Sources/XcodesKit/XcodeList.swift
  Sources/xcodes/App.swift
  Tests/XcodesKitTests/Environment+Mock.swift
  Tests/XcodesKitTests/XcodesKitTests.swift
Labels: hacktoberfest

#182 Add select option to install
  Sources/XcodesKit/XcodeInstaller.swift
  Sources/XcodesKit/XcodeSelect.swift
  Sources/xcodes/App.swift
Labels: enhancement

#237 Add contributing guide
  CONTRIBUTING.md
Labels: chore
